import type { APIRoute } from 'astro';
import blogData from '../data/blog-posts.json';
import lastmodManifest from '../data/page-lastmod.json';
import type { BlogPost } from '../types/blog';

const SITE_URL = 'https://hypedigitaly.ai';

/**
 * Lastmod Manifest Type
 * Generated by scripts/generate-lastmod.js from Git commit dates
 */
interface LastmodManifest {
  generated: string;
  description: string;
  pages: Record<string, string>;
  blogPostsLastMod: string;
}

// Type assertion for the imported manifest
const manifest = lastmodManifest as LastmodManifest;

/**
 * Static pages with their priorities and change frequencies
 * lastmod is now pulled automatically from Git-generated manifest
 * 
 * NOTE: The lastmod dates are auto-generated from Git commit history.
 * When you modify a page file and push to GitHub, the sitemap will
 * automatically reflect the correct lastmod date on next build.
 */
const staticPages = [
  { path: '/', priority: 1.0, changefreq: 'weekly' },
  { path: '/chatbot', priority: 0.9, changefreq: 'monthly' },
  { path: '/konzultace', priority: 0.8, changefreq: 'monthly' },
  { path: '/priprava-dat', priority: 0.8, changefreq: 'monthly' },
  { path: '/blog', priority: 0.7, changefreq: 'weekly' },
  { path: '/privacy-policy', priority: 0.3, changefreq: 'yearly' },
  { path: '/recommendation', priority: 0.3, changefreq: 'yearly' },
];

/**
 * Get the lastmod date for a static page from the Git-generated manifest
 * @param path - URL path (e.g., '/', '/chatbot')
 * @returns Date string in YYYY-MM-DD format
 */
function getPageLastmod(path: string): string {
  return manifest.pages[path] || new Date().toISOString().split('T')[0];
}

/**
 * Get the lastmod date for blog posts from the Git-generated manifest
 * All blog posts share the same lastmod based on when blog-posts.json was last committed
 * @returns Date string in YYYY-MM-DD format
 */
function getBlogLastmod(): string {
  return manifest.blogPostsLastMod || new Date().toISOString().split('T')[0];
}

/**
 * Generate a single URL entry for the sitemap
 */
function generateUrlEntry(
  loc: string, 
  lastmod: string, 
  changefreq: string, 
  priority: number,
  alternates?: { lang: string; href: string }[]
): string {
  let entry = `  <url>
    <loc>${loc}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${changefreq}</changefreq>
    <priority>${priority.toFixed(1)}</priority>`;
  
  // Add hreflang alternates for multilingual support
  if (alternates && alternates.length > 0) {
    alternates.forEach(alt => {
      entry += `
    <xhtml:link rel="alternate" hreflang="${alt.lang}" href="${alt.href}" />`;
    });
  }
  
  entry += `
  </url>
`;
  
  return entry;
}

export const GET: APIRoute = async () => {
  const blogPosts = blogData.posts as BlogPost[];
  const blogLastMod = getBlogLastmod();
  
  let sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/sitemap.xsl"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
`;

  // Add static pages with Git-based lastmod dates
  for (const page of staticPages) {
    const pageLastmod = getPageLastmod(page.path);
    const csUrl = `${SITE_URL}${page.path}`;
    const enUrl = `${SITE_URL}${page.path}${page.path === '/' ? '?lang=en' : '?lang=en'}`;
    
    // Czech version (default - clean URL)
    sitemap += generateUrlEntry(
      csUrl,
      pageLastmod,
      page.changefreq,
      page.priority,
      [
        { lang: 'cs', href: csUrl },
        { lang: 'en', href: enUrl },
        { lang: 'x-default', href: csUrl }
      ]
    );
    
    // English version
    sitemap += generateUrlEntry(
      enUrl,
      pageLastmod,
      page.changefreq,
      page.priority - 0.1, // Slightly lower priority for alternate language
      [
        { lang: 'cs', href: csUrl },
        { lang: 'en', href: enUrl },
        { lang: 'x-default', href: csUrl }
      ]
    );
  }

  // Add blog posts - all use the blog-posts.json last Git commit date
  for (const post of blogPosts) {
    const csUrl = `${SITE_URL}/blog/${post.slug}`;
    const enUrl = `${SITE_URL}/blog/${post.slug}?lang=en`;
    
    // Czech version
    sitemap += generateUrlEntry(
      csUrl,
      blogLastMod,
      'monthly',
      0.6,
      [
        { lang: 'cs', href: csUrl },
        { lang: 'en', href: enUrl },
        { lang: 'x-default', href: csUrl }
      ]
    );
    
    // English version
    sitemap += generateUrlEntry(
      enUrl,
      blogLastMod,
      'monthly',
      0.5,
      [
        { lang: 'cs', href: csUrl },
        { lang: 'en', href: enUrl },
        { lang: 'x-default', href: csUrl }
      ]
    );
  }

  sitemap += `
</urlset>`;

  return new Response(sitemap, {
    headers: {
      'Content-Type': 'application/xml; charset=utf-8',
      'Cache-Control': 'public, max-age=3600' // Cache for 1 hour
    }
  });
};
